# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Firebase App Distribution"
  lane :deploy_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
    release = firebase_app_distribution(
      app: "1:1024985606183:android:c0b430a2bb2ef05dba0602",
      testers: "hassanaboeata@gmail.com",
      release_notes: "Initial FastLane Firebase Distribution",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end
 
end
